### ISSUE TITLE
Plattform-Unterstützung und Vielfalt der möglichen Graphen

### ISSUE THREAD

**Issue by Jak2k** [j-schall/FunctionVisualizer#1]
# Plattform-Unterstützung

**Java verspricht eine große Plattform-Unterstützung.** Der Erfolg Javas entstand aus dem Versprechen, dass ein Java-Programm überall läuft. **Dies ist in der Praxis aber nicht der Fall** (wie du selbst bemerkt hast). Deshalb wurde Java mit der Zeit von JavaScript abgelöst. JavaScript ist *wirklich* überall lauffähig: Vom kleinen Rassbery Pi mit Chromium, über Android Smartphones mit Chrome und iphones mit Safari, bis hin zu Linux-Computern mit Firefox.

# Vielfalt der möglichen Graphen

Soweit ich sehe, implementierst du alle Graph-Typen einzeln. Dies wird aber niemals alle Funktions-Arten zulassen. Was du bräuchtest, wäre eine eine Funtion, die jede mathematische Funktion aus einem string parsen kann. Das ist allerdings sehr viel Aufwand. Deshalb gibt es Libraries wie math.js, die das bereits für dich erstellt haben.

- [code](https://mathjs.org/examples/browser/plot.html.html)
- [Beispiel](https://mathjs.org/examples/browser/plot.html)

*P. S.: Deutschsprachiger Code bzw. Commits gelten als unprofessionell.*
*P. P. s.: Statt Java würde ich grundsätzlich immer JavaScript/TypeScript oder rust empfehlen*

**Comment by jschxll** [comment]
**Plattform Unterstützung**
Ich have gerade die *.jar zu den Realises hinzugefügt. Damit ist das Programm plattformunabhänig. Wenn du möchtest kannst du es dir mal anschauen;)

P.S: Kannst du mir Feedback geben, falls du es dir angeschaut hast?

**Comment by Jak2k** [comment]
Es ist **nicht plattformunabhängig**:

- Es ist nicht auf Android (dem verbreitetsten End-Nutzer-OS¹) oder iOS ausführbar.
- Es enthält haufenweise Windows-Libraries (.dll)

Ich versuche heute Abend, das Progamm auf meinem Computer zu starten.

*1: Android wird auf 50% der End-Geräte genutzt.*

**Comment by jschxll** [comment]
Danke, daran hatte erlichgesagt ich nicht mehr gedacht, dass .dll nur für Winows ist😅. Ich probiere die UI Library für Linux bereitzustellen. Mit "Plattformunabhänig" wollte ich erstmal sagen, dass das Programm auf allen Computersystemen ausführbar wird.

**Comment by Jak2k** [comment]
***Du müsstest aber auch noch für Mac, Android und so weiter bereitstellen. Wie gesagt, ultimative Plattformunabhängigkeit geht nur im Web.***

JavaScript ähnelt Java in vielen Punkten. Du musst halt keine Klassen nutzen und viel Sachen sind etwas logischer (manchmal auch dümmer). Mit [TypeScript](https://www.typescriptlang.org/) bekommst du auch statisches partial-opt-out Typing. Das heißt du weißt Variablen-/Funtktions-/...-typen zu, wo du aber keine Lust hast, sagst du der Type ist `any`. Die Sprache ist wirklich sehr einfach zu lernen und du kannst dann Schrittweise immer mehr Technologien wie Bundler, Framworks, Linter, CI und so nutzen, wenn du bereit dazu bist. Ein minimales JavaScript-Projekt besteht aus einer einzelnen html-Datei, während ein großes Projekt hunderte Libraries und Build-Schritte haben kann. Die native Integration von WebApps schreitet mit PWAs auch schnell voran.

**Comment by jschxll** [comment]
Ja, du hast recht das Javascript bzw. Typescript in vielen Punkten wahrscheinlich wesentlich einfacher wäre, als Java, da man viel mit statischen- oder auch nicht-statischen Kontexten und Klassen hantieren muss, aber ich mag das Exceptionhandling und die typsiichere Art von Java. Ich werde auch irgendwann Javascript lernen, aber das Projekt möchte ich auf jeden Fall noch mit Java beenden. Wie auch du schon gesagt hast ist das Web, die beste Wahl um plattformumabhängige Projekte zu machen.

**Comment by Jak2k** [comment]
- Exeption-Handling: try-catch funktioniert in Java und JavaScript fasst exakt gleich. (Wobei dert Ansatz von rust generell überlegen ist.)
- Type-Sicherheit: Wenn du Typescript nutzt, hast du (solange du nicht `any`) nutzt auch ein statisches Type-System. Es gibt auch mächtige Konzepte wie Conditional-Typing oder Parameter in Types.

Noch zum Thema Klassen: JavaScript hat auch Klassen, auch wenn diese nicht besonder beliebt sind. Das Erstellen von UI kann auch durch zahlreiche Libraries wie zum Beispiel [Vue](https://vuejs.org/) vereinfacht werden.

*P. S.: Was ist mit deinem Profilbild passiert?*

**Comment by Jak2k** [comment]
Auf meinem Linux Rechner bekomme ich: `Error: JavaFX runtime components are missing, and are required to run this application`

**Comment by jschxll** [comment]
Im Readme ist ganz unten ein Link zu den Javafx Komponenten. Die musst du runterladen, um das Peogramm zu starten.
Dann führst du den Befehl, aus dem Readme aus, aber ersetzt den Pfad, durch zu den runtergeladenen Javafx Komponenten, bis zum Ordner ./lib.

**Comment by jschxll** [comment]
Besteht immernoch das Problem?
